version: "3.9"
services:
  web:
    build: 
      dockerfile: ./dockerfile/Dockerfile
      context: .
    ports:
      - "3001:8080"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules

volumes:
  node_modules: